name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the project (compile TypeScript)
      - name: Build project
        run: npm run build
        env:
          CI: false

      # 5. (Optional) Copy static files like index.html to the dist folder.
      # Remove or modify this step if your build process already handles static files.
      - name: Copy static files
        run: cp index.html dist/
